# Generated by Django 5.2.4 on 2025-08-01 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 13, 32, 20, 2135, tzinfo=datetime.timezone.utc)),
        ),
    ]
